# Generated by Django 6.0.5 on 2026-06-25 02:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20260624_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPendingOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('payload', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='users.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrador'), ('ADMIN', 'Admin'), ('APRENDIZ', 'Aprendiz'), ('MONITOR', 'Monitor'), ('INSTRUCTOR', 'Instructor')], max_length=50),
        ),
    ]
