# Generated by Django 6.1.1 on 2026-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaldictionary',
            name='competence',
            field=models.CharField(blank=True, choices=[('Speaking', 'Speaking'), ('Grammar', 'Grammar'), ('Writing', 'Writing'), ('Reading', 'Reading')], default='Grammar', max_length=20),
        ),
        migrations.AddField(
            model_name='digitaldictionary',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], default='A1', max_length=10),
        ),
    ]
