# Generated by Django 5.2.13 on 2026-10-06 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_digitaldictionary_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('ficha_code', models.CharField(max_length=50)),
                ('program_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_requests', to='users.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ficha_requests', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_requests', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
