services:
  worklex_auth_keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: worklex_auth_keycloak

    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}

    command: start-dev

    expose:
      - "8080:8080"

    networks:
      - worklex_private_network

networks:
  worklex_private_network:
    internal: true