services:
  worklex_vault:
    image: hashicorp/vault:latest
    container_name: worklex_vault

    expose:
      - "8200"

    cap_add:
      - IPC_LOCK

    volumes:
      - ./config:/vault/config
      - ./data:/vault/data
      - ./logs:/vault/logs

    command: vault server -config=/vault/config/vault.hcl

    networks:
      - worklex_app_network

networks:
  worklex_data_network:
    driver: bridge
    name: worklex_app_network
