services:

  worklex_proxy:

    image: owasp/modsecurity-crs:nginx

    container_name: worklex_proxy

    restart: unless-stopped

    ports:
      - "80:8080"
      - "443:8443"

    depends_on:
      - worklex_backend
      - worklex_frontend
      - worklex_minio

    volumes:

      - ./proxy/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro

      - ./proxy/conf.d/worklex.conf:/etc/nginx/templates/conf.d/default.conf.template:ro

      - ./proxy/modsecurity/modsecurity-override.conf:/etc/nginx/templates/modsecurity.d/modsecurity-override.conf.template:ro
      - ./proxy/modsecurity/setup.conf:/etc/nginx/templates/modsecurity.d/setup.conf.template:ro

      - ./proxy/logs:/var/log/nginx

      - ./certbot/conf:/etc/letsencrypt

      - ./certbot/www:/var/www/certbot

    networks:
      - worklex_network

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - NET_RAW

    read_only: false

    tmpfs:
      - /tmp
      - /var/run

    healthcheck:

      test: ["CMD-SHELL", "nginx -t || exit 1"]

      interval: 30s

      timeout: 10s

      retries: 3

    logging:

      driver: json-file

      options:
        max-size: "50m"
        max-file: "5"

    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 200M

  worklex_certbot:

    image: certbot/certbot:v2.11.0

    container_name: worklex_certbot

    profiles:
      - ssl

    entrypoint: ["sh", "-c"]
    command: >
      "while :; do
      certbot renew;
      sleep 12h;
      done"

    restart: unless-stopped

    volumes:

      - ./certbot/conf:/etc/letsencrypt

      - ./certbot/www:/var/www/certbot

    depends_on:
      - worklex_proxy

    networks:
      - worklex_network

    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 64M

networks:

  worklex_network:
    name: worklex_network
    driver: bridge