services:

  worklex_proxy_nginx:

    image: owasp/modsecurity-crs:nginx

    container_name: worklex_proxy_nginx

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:

      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf.d:/etc/nginx/conf.d:ro
      - ./proxy/modsecurity:/etc/modsecurity.d:ro
      - ./proxy/logs:/var/log/nginx:rw
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

    networks:
      - worklex_edge_network
      - worklex_app_network
      - worklex_data_network

    security_opt:
      - no-new-privileges:true

    cap_drop:
      #- NET_RAW
      - ALL

    read_only: true

    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

    healthcheck:
      #test: ["CMD-SHELL", "nginx -t || exit 1"]
      test: ["CMD-SHELL", "nginx -t && nginx -s reload >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

  worklex_certbot:

    image: certbot/certbot

    container_name: worklex_certbot
    
    command: >
      sh -c "while :; do
      certbot renew;
      sleep 12h;
      done"

    restart: unless-stopped

    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    depends_on:
      - worklex_proxy_nginx

    networks:
      - worklex_app_network

# Preparado para futuras expansiones
#    worklex_logs:

networks:
  worklex_edge_network:
    external: true
    name: worklex_edge_network

  worklex_app_network:
    external: true
    name: worklex_app_network

  worklex_data_network:
    external: true
    name: worklex_data_network
