services:
  worklex_IDS_IPS_crowdsec:
    image: crowdsecurity/crowdsec

    container_name: worklex_IDS_IPS_crowdsec

    volumes:
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml

    networks:
      - worklex_data_network

networks:
  worklex_data_network:
    driver: bridge
    name: worklex_data_network