services:
  vault:
    image: hashicorp/vault:1.15.6
    container_name: worklex_vault
    profiles:
      - vault

    ports:
      - "8200:8200"

    cap_add:
      - IPC_LOCK

    volumes:
      - ./config:/vault/config
      - ./data:/vault/data
      - ./logs:/vault/logs

    command: vault server -config=/vault/config/vault.hcl

    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 128M

    networks:
      - worklex_network

networks:
  worklex_network:
    name: worklex_network
    driver: bridge