# Generated by Django 6.0.5 on 2026-06-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_testresult_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='process',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
