# Generated by Django 6.0.5 on 2026-06-25 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_emailotp'),
    ]

    operations = [
    ]
