# Generated by Django 5.2.13 on 2026-07-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaldictionary',
            name='category',
            field=models.CharField(choices=[('GRAMMAR', 'Grammar'), ('SPEAKING', 'Speaking'), ('WRITING', 'Writing'), ('LISTENING', 'Listening'), ('MULTIMEDIA', 'Multimedia')], default='MULTIMEDIA', max_length=30),
        ),
    ]
