# Generated by Django 5.2.13 on 2026-10-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_digitaldictionary_competence_digitaldictionary_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, default='Colombia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='level',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='level',
            field=models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Elemental'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Maestría'), ('Sin Nivel', 'Sin Nivel / No Presentado')], default='Sin Nivel', max_length=25),
        ),
    ]
