# Generated by Django 5.2.13 on 2026-07-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_digitaldictionary_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaldictionary',
            name='audio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='digitaldictionary',
            name='definition',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='digitaldictionary',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='digitaldictionary',
            name='synonyms',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='digitaldictionary',
            name='video',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='digitaldictionary',
            name='word_id',
            field=models.CharField(max_length=255),
        ),
    ]
