# Generated by Django on 2026-10-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_person_country_alter_ranking_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaldictionary',
            name='program',
            field=models.CharField(blank=True, db_index=True, default='ADSO', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='level',
            field=models.CharField(
                choices=[
                    ('A1', 'A1 - Principiante'),
                    ('A2', 'A2 - Elemental'),
                    ('B1', 'B1 - Intermedio'),
                    ('B2', 'B2 - Intermedio Alto'),
                    ('C1', 'C1 - Avanzado'),
                    ('C2', 'C2 - Maestría'),
                    ('Sin Nivel', 'Sin Nivel / No Presentado'),
                    ('Invalidada', 'Prueba Invalidada'),
                    ('No Presentado', 'No Presentado'),
                ],
                default='Sin Nivel',
                max_length=25,
            ),
        ),
    ]
