# Generated by Django 5.2.13 on 2026-07-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_digitaldictionary_audio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='digitaldictionary',
            unique_together=set(),
        ),
    ]
