# Generated by Django 5.2.13 on 2026-07-10 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_insert_default_subjects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='digitaldictionary',
            unique_together={('word_id', 'subject')},
        ),
    ]
