# Generated by Django 5.2.13 on 2026-07-18 06:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_training_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaldictionary',
            name='ficha',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='digitaldictionary',
            name='program',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='digitaldictionary',
            name='audio',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='digitaldictionary',
            name='image',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='level',
            field=models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Elemental'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto')], max_length=10),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('program', models.CharField(max_length=120)),
                ('ficha', models.CharField(blank=True, default='', max_length=50)),
                ('word_id', models.CharField(blank=True, default='', max_length=255)),
                ('definition', models.CharField(blank=True, default='', max_length=500)),
                ('synonyms', models.CharField(blank=True, default='', max_length=500)),
                ('bucket', models.CharField(max_length=100)),
                ('object_key', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['media_type', 'program', 'ficha'], name='users_media_media_t_236cfc_idx'), models.Index(fields=['program', 'ficha', 'media_type'], name='users_media_program_7886b5_idx')],
            },
        ),
    ]
