# Generated by Django 5.2.13 on 2026-07-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_digitaldictionary_ficha_digitaldictionary_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaldictionary',
            name='difficulty',
            field=models.IntegerField(default=2),
        ),
    ]
